feat: use api key for openapi
coscene-io/sample-json-api-files pull request #2
Opened 2022-12-10 04:57 UTC by renyijiu

2022-12-12 13:08 UTC, leonmax requested changes

2022-12-13 03:38 UTC, yujingz commented on README.md
> +3. 输入地址 `http://127.0.0.1:31338/swagger.json` 查看即可获取到接口文档
我们在 oss 上挂一个让他直接打开吧

2022-12-13 03:38 UTC, yujingz approved these changes

2022-12-13 03:40 UTC, renyijiu commented on README.md
> +3. 输入地址 `http://127.0.0.1:31338/swagger.json` 查看即可获取到接口文档
后续部署单独的openapi站点，这个swagger文件就用不到了

2022-12-13 03:48 UTC, yujingz commented on README.md
> +3. 输入地址 `http://127.0.0.1:31338/swagger.json` 查看即可获取到接口文档
k yeah no biggie. lets go!

2022-12-13 03:50 UTC, merged