feat: add sha256 for artifacts
coscene-io/sample-json-api-files pull request #32
Opened 2023-06-01 07:06 UTC by renyijiu

2023-06-05 09:00 UTC, leonmax commented on cos/collector.py
> +        updater_state = UpdaterState(0)
作为内部状态，可以考虑封装在 updater 里面，继承 BaseState 可以更简单 persist状态

2023-06-05 09:00 UTC, leonmax commented on cos/updater.py
> +    def _check_systemd_service():
客户需要限制 CPU 怎么办呢？这个应该是可以直接从 config 渲染的 template

2023-06-05 09:00 UTC, leonmax commented on cos/updater.py
> +        return True, remote_version
没必要返回 tuple 吧，None 就是不更新，有就是更新？

2023-06-05 09:00 UTC, leonmax commented on cos/updater.py
> +            _log.info("updater is not due yet")
同上

2023-06-05 09:00 UTC, leonmax commented on cos/updater.py
> +            _log.info("updater is disabled")
太多 log 了，这个写 debug 吧。否则每分钟都是这条没用的

2023-06-05 09:00 UTC, leonmax commented on cos/updater.py
> +            _log.info("checking for updates")
同上

2023-06-05 09:00 UTC, leonmax commented on cos/updater.py
> +                _log.info("no new version available")
同上

2023-06-05 09:00 UTC, leonmax commented on cos/updater.py
> +                self.restart_systemd_service()
这是假设目前的进程使用 systemd 启动的？万一不是的话重启是不是会有两个进程？考虑用 pid file 来管理？

2023-06-05 09:00 UTC, leonmax commented on cos/updater.py
> +        r = run(["systemctl", "restart", SERVICE_ID], capture_output=True)
这里可能还是需要 daemon-reload？

2023-06-05 09:00 UTC, leonmax requested changes
好几个地方需要讨论， 有需要电话我

2023-06-05 09:00 UTC, leonmax requested changes
好几个地方需要讨论， 有需要电话我

2023-06-05 09:00 UTC, leonmax requested changes
好几个地方需要讨论， 有需要电话我

2023-06-05 09:00 UTC, leonmax requested changes
好几个地方需要讨论， 有需要电话我

2023-06-05 09:00 UTC, leonmax requested changes
好几个地方需要讨论， 有需要电话我

2023-06-05 09:00 UTC, leonmax requested changes
好几个地方需要讨论， 有需要电话我

2023-06-05 09:00 UTC, leonmax requested changes
好几个地方需要讨论， 有需要电话我

2023-06-05 09:00 UTC, leonmax requested changes
好几个地方需要讨论， 有需要电话我

2023-06-05 09:03 UTC, renyijiu commented on .github/workflows/build.yml
> +            dist/version
多个 artifacts 会打成一个压缩包，不想修改你的本地部署脚本

2023-06-05 09:04 UTC, renyijiu commented on cos/tools.py
> +            if 0 < count_down < len(byte_block):
这里有bug，不传入size计算的sha256是错误的，具体可以看测试

2023-06-05 09:05 UTC, renyijiu commented on cos/updater.py
> +    def _check_systemd_service():
本地部署完成之后不会修改 systemd，升级程序不和更新配置挂钩

2023-06-09 16:25 UTC, leonmax approved these changes

2023-06-09 16:25 UTC, merged